# Generated by Django 5.1.3 on 2024-12-14 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='parts_used',
            new_name='parts',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner_name',
            new_name='make',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='rack_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_contact',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_details',
        ),
        migrations.AddField(
            model_name='bill',
            name='service_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 14, 16, 55, 171666, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billpart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
    ]
