# Generated by Django 5.1.3 on 2024-12-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_parts_used_bill_parts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='quantity_in_stock',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='part',
            name='rack_number',
            field=models.CharField(default='A1', max_length=50),
            preserve_default=False,
        ),
    ]
