# Generated by Django 5.1.3 on 2024-12-14 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_in_stock_part_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_plate',
            new_name='registration_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='servicing_details',
            field=models.TextField(default='Initial service record'),
            preserve_default=False,
        ),
    ]
