# Generated by Django 5.1.3 on 2024-12-14 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_vehicle_other_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='parts',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='service_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='rack_number',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='DEFAULT001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='Customer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='serial_number',
            field=models.CharField(default='SN0001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='BillPart',
        ),
    ]
