# Generated by Django 5.1.3 on 2025-02-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_vehicle_description_vehicle_parts_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='service_date',
            field=models.DateField(default=datetime.date(2025, 2, 16)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
    ]
