# Generated by Django 5.1.3 on 2025-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_vehicle_service_date_alter_bill_bill_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='part',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=20),
        ),
    ]
