# Generated by Django 5.1.3 on 2025-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_bill_updated_at_remove_part_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='parts_used',
            field=models.ManyToManyField(blank=True, related_name='bills', to='inventory.part'),
        ),
    ]
